{
    'name': 'Crear Orden de Venta desde Albarán',
    'version': '19.0.1.13.0',
    'category': 'Sales/Sales',
    'summary': 'Permite crear órdenes de venta a partir de albaranes',
    'author': 'Francisco Jose Carrion',
    'license': 'AGPL-3',
    'depends': [
        'sale_management',
        'sale_renting',
        'sale_stock_renting',
        'stock',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/sale_order_views.xml',
        'wizard/rental_order_rename_wizard_view.xml',
        'wizard/sale_order_missing_import_wizard_view.xml',
        'views/stock_picking_views.xml',
        'views/rental_loss_report_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
