from . import product_facet
from . import product_tag
from . import product_template
from . import product_product
from . import res_company
from . import res_config_settings
from . import res_partner
from . import sale_order
from . import sale_order_line
